spring.application.name=merklist
spring.datasource.url=jdbc:mysql://localhost:3306/merklist
spring.datasource.username=merklist_user
spring.datasource.password=software2026!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8080

