spring.datasource.url=jdbc:mysql://localhost:3306/merklist
spring.datasource.username=merklist_user
spring.datasource.password=Software2026!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
logging.level.root=INFO
logging.level.com.merklist=DEBUG